app = angular.module "racoon", ["ui.router","ui.keypress","ui.event",'angular-loading-bar', 'ngAnimate', 'anim-in-out']


whichTransitionEvent = ->
  t = undefined
  el = document.querySelector(".full-modal")
  transitions =
    'transition': 'transitionend'
    'OTransition': 'oTransitionEnd'
    'MozTransition': 'transitionend'
    'WebkitTransition': 'webkitTransitionEnd'
  for t of transitions
    if el.style[t] != undefined
      return transitions[t]



  app.config ['cfpLoadingBarProvider', (cfpLoadingBarProvider) =>
    cfpLoadingBarProvider.includeSpinner = false
    cfpLoadingBarProvider.latencyThreshold = 0;

  ]

app.config ($stateProvider, $urlRouterProvider) ->
  $stateProvider.state('dummy',
    url: "/dummy",
    templateUrl: "views/dummy_text.html"
  )
  .state('modals'
    url: "/modals",
    templateUrl: "views/modals.html"
  )
  $urlRouterProvider.otherwise("/")


app.controller "BodyController", ["$scope", ($scope)=>
  $scope.dummy = "Morphing Button "

]

app.controller "ModalController", ["$scope", ($scope)=>
  $scope.modalState = "closed"




  $scope.toggleState = () ->
    $scope.modalState = if $scope.modalState == "closed" then "opened" else "closed"


  $scope.dismiss = () ->
    $scope.modalState = "closed"


]




### Listen for a transition! ###


### From Modernizr ###


###
	The "whichTransitionEvent" can be swapped for "animation" instead of "transition" texts, as can the usage :)
###

# ---
# generated by js2coffee 2.0.1
